Assignment 6.1

Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

Note: Solution submitted via github must contain all the detailed steps.

In [11]:

import numpy as np
# Function vander_func
#  1st Param : lst is a list
#  2nd Param : N is the order of power
#  3rd Param : sorting order 
def myVanderFunc(lst,N,ascending=False):
    if ascending:
        return np.sort(np.column_stack([lst**(N-1-i) for i in range(N)]),axis=1)
    else:
        return np.column_stack([lst**(N-1-i) for i in range(N)])
    

default=myVanderFunc(np.array([1, 3, 6, 7]),3)
print("My Vandermonde Function - default :\n" , default)

ascending=myVanderFunc(np.array([1, 3, 6, 7]),3,True)
print("My Vandermonde Function - ascending order :\n" , ascending)

My Vandermonde Function - default :
 [[ 1  1  1]
 [ 9  3  1]
 [36  6  1]
 [49  7  1]]
My Vandermonde Function - ascending order :
 [[ 1  1  1]
 [ 1  3  9]
 [ 1  6 36]
 [ 1  7 49]]


In [14]:
# Using Vander Function
arr1 = np.array([1,3,6,7])
N=3
vander1 = np.vander(arr1,N)
print(vander1)

[[ 1  1  1]
 [ 9  3  1]
 [36  6  1]
 [49  7  1]]


In [15]:
vander2 = np.vander(arr1,N, increasing=True)
print(vander2)

[[ 1  1  1]
 [ 1  3  9]
 [ 1  6 36]
 [ 1  7 49]]
